### ISSUE TITLE
Ahrweiler-TODO

### ISSUE THREAD

**Issue by leofeyer** [contao/symfony-todo#3]
- [ ] FIXMEs
- [ ] Pull-Requests und Tickets
- [ ] Frontent-Preview reparieren
- [ ] Unit-Tests für zirkuläre Load-After-Definitionen
- [ ] Doctrine-Driver fertig machen
  - [ ] Remove database driver select field in install tool
  - [ ] Upgrade `localconfig.php` if it uses one of the legacy drivers
- [ ] Unit-Test für alles Ungetestete
- [ ] Bootstrap fertig machen
  - [ ] Die vier Includes aus der `bootstrap.php` ins CoreBundle
- [ ] Twig-Konfiguration mit Standard-Edition abgleichen
- [ ] `UPGRADE.md` ergänzen
  - [ ] neue Pfade im BE
  - [ ] kein `if (TL_SCRIPT == 'contao/install.php')` mehr
- [ ] Installtool anpassen (bzw. Stand-Alone)
  - [ ] DB-Zugangsdaten jetzt in `parameters.yml`
  - [ ] Encryption-Token jetzt in `parameters.yml`
- [ ] Twig Minimum-Version 1.5 sollte required werden (für `dump()`)
- [ ] `Template::path()` bzw. `Template::route()`
- [ ] `TL_MODE` und Container-Scope in einem Listener setzen (@Toflar)
- [ ] Response implements Indexable mit Methode getPageObject()
- [ ] Response-Exception (siehe Error-Logging-PR)
  - [ ] Contao-Exception-Listener in `app_dev.php` nicht registrieren?
- [ ] Authentication für `app_dev.php` (@aschempp)
- [ ] Alle Services, die nur injected werden, sollten public=false sein (@aschempp)
- [ ] `kernel.contao_bundles` (siehe `kernel.bundles`)
- [ ] `initialize.php` SAPI-Check (@discordier)
- [ ] Fix whitespace in the new files
- [ ] Nur State-Informationen in die DB-Session schreiben
  - [ ] Referer- und Token-Management in $_SESSION
- [ ] BundleLoader und RoutingLoader
- [ ] Doku schreiben (RC-Phase)
- [ ] Extensions testen (RC-Phase)

**Comment by aschempp** [comment]
Die Twig-Konfiguration entspricht bereits der symfony/standard-edition

**Comment by leofeyer** [comment]
@Toflar @aschempp Was ist mit dem Punkt "`TL_MODE` und Container-Scope in einem Listener setzen"? Hattet ihr nicht besprochen, dass die beiden separat bleiben sollen? Dann könnten wir den Punkt nämlich abhaken.

**Comment by aschempp** [comment]
Hatten wir bereits im anderen Ticket diskutiert. Ich hab hier gesucht aber nicht gefunden… ist abgehakt.

**Comment by leofeyer** [comment]
:+1:

**Comment by leofeyer** [comment]
Die aktuelle Twig-Version wäre 1.18. Soll ich trotzdem `~1.5` angeben?

**Comment by aschempp** [comment]
> Die aktuelle Twig-Version wäre 1.18. Soll ich trotzdem ~1.5 angeben?

Scheint mir komisch. Welche Version hat @discordier denn installiert dass im `dump` fehlt?

**Comment by leofeyer** [comment]
Hab gerade mal in der `installed.json` nachgesehen und dort wurde auch die Version 1.18 installiert. Symfony selbst fordert bei mir die Version `~1.12,>=1.12.3` an.

**Comment by leofeyer** [comment]
Ich habe jetzt mal die Symfony-Version übernommen, damit wir voran kommen :)

**Comment by Toflar** [comment]
@discordier können wir in absehbarer Zeit dein Error Reporting/ResponseException-Branch fertig kriegen? Ich würd mich gern dem `Response implements Indexable mit Methode getPageObject()` annehmen. Heute Abend da? Wenn nicht würde ich wenigstens noch einen PR für `Template::path() bzw. Template::route()` bis morgen fertig machen. So als Heads-Up für alle, damit wir nicht doppelte Arbeit haben.

**Comment by Toflar** [comment]
Bezüglich zirkulärer Abhängigkeiten beim Autoload-Resolving. Da kommt eine `UnresolvableLoadingOrderException`. Siehe https://github.com/contao/core-bundle/blob/develop/tests/Autoload/ConfigResolverTest.php#L74.
Mir war doch ich hätte den Test geschrieben. Dem war offensichtlich so :-) (https://github.com/contao/core-bundle/commit/5f7a937064e458661919fa684172b525b59edc50)

**Comment by discordier** [comment]
Ich bin leider aktuell ein wenig arg eingespannt und krieg es heute nicht mehr hin. Evtl. bis morgen zum call zumindest soweit dass wir die erste Basis haben.

Bin mit ein paar Details noch nicht glycklich aber die besprechen wir dann.

@Toflar deinen letzten Kommentar verstehe ich nicht ganz, auf was konkret beziehst du dich damit? Das ist eine andere exception als die die wir deprecaten?

**Comment by Toflar** [comment]
> @Toflar deinen letzten Kommentar verstehe ich nicht ganz, auf was konkret beziehst du dich damit? Das ist eine andere exception als die die wir deprecaten?

Joa es hat ein ToDo für "Unit-Tests für zirkuläre Load-After-Definitionen" - das meinte ich :)

**Comment by aschempp** [comment]
Das *Unit-Tests für zirkuläre Load-After-Definitionen* war anders gemeint. Die Frage war was passiert wenn mehrere Bundles dieselbe Komponente laden und ein "load-after" definieren. Werden die "load-after" gemergt oder überschrieben?

**Comment by Toflar** [comment]
Tut, hier wäre der unit test: https://github.com/contao/core-bundle/pull/56

**Comment by leofeyer** [comment]
Was machen wir denn jetzt mit der `system/initialize.php`? Der Composer-ScriptHandler legt sie aktuell nicht an. Sollte er das tun und wenn ja, was steht dann in der Datei drin?

**Comment by Toflar** [comment]
Naja, für BC müsste sie wie gewohnt das System hochfahren. Ich glaube einfach, dass das nie zuverlässig funktionieren wird. Für mich wär's auch OK einfach zu sagen, dass Custom-Entry-Scripts nicht mehr möglich sind in der 4. Man soll sich eine eigene Route schreiben. Wie seht ihr das?

**Comment by leofeyer** [comment]
Funktioniert denn z.B. der eigene Entry-Point von Isotope, wenn in der `system/initialize.php` nur steht:

```php
require_once __DIR__ . '/../app/bootstrap.php.cache';
require_once __DIR__ . '/../app/AppKernel.php';

$kernel = new AppKernel('prod', false);
$kernel->loadClassCache();
$kernel->loadBundleCache();
$kernel->boot();
```

**Comment by aschempp** [comment]
in der Initial-Version schon. Seit der Listener eine Route braucht nicht mehr, das wollten wir ja noch anpassen.

**Comment by leofeyer** [comment]
Was genau müsste ich da anpassen?

**Comment by aschempp** [comment]
Einen Request durch den Kernel jagen und die Response ignorieren…

**Comment by leofeyer** [comment]
Hm, nicht schön das ist :(

**Comment by Toflar** [comment]
Wie gesagt, wir alle wissen zusätzliche Entry-Points falsch sind. Wir können auch gemeinsam beschliessen das einfach nicht mehr zu supporten. 99% aller Extensions betrifft das eh nicht.

**Comment by aschempp** [comment]
Es ist nicht schön, aber würde bei den wenigen dafür sorgen dass es funktioniert. BC war erklärtes Ziel, es gibt keinen Grund das nicht einzubauen nur weil es unschön ist. BC ist immer unschön.

**Comment by leofeyer** [comment]
Ich glaube wir übersehen hier etwas. Bei einem Custom-Entry-Point sind `TL_MODE` und `TL_SCRIPT` ja schon gesetzt, oder?

**Comment by Toflar** [comment]
Für die ganze Session-Sache (nur State-Info in der DB etc.) müssen wir ja ohnehin an der Session rumschrauben. Denkt ihr es wäre ein Versuch wert, auf die SF-Session umzustellen oder gibt es irgendwas was dagegen spricht?

**Comment by leofeyer** [comment]
Abgesehen davon, dass die geplante Änderung nichts mit dem Storage-Layer zu tun hat, spricht meines Erachtens nichts dagegen. Ich hatte dazu auch schon contao/contao#60 aufgemacht.

**Comment by leofeyer** [comment]
@aschempp Hast Du den Punkt "Data-Collector anpassen und Tests dafür schreiben" angehakt? Die Klasse ist bei mir nämlich noch ungetestet. Liegen die Tests bei Dir?

**Comment by aschempp** [comment]
Ich habe das vermutlich angehakt, weil ich wusste dass mein PR bezüglich der Anpassung gemergt wurde, und weil es sowieso einen Punkt "Tests für alles ungetestete" gibt ;-)

**Comment by leofeyer** [comment]
Wäre cool, wenn Du die Tests noch schnell schreiben könntest ;)

**Comment by aschempp** [comment]
Kann ich frühestens nächste Woche…

**Comment by Toflar** [comment]
> Response implements Indexable mit Methode getPageObject() (@Toflar)

Hab mir das heute mal angesehen und für den falschen Weg befunden. Die Response selber weiss nicht ob sie indexiert werden soll, geschweige denn wie. Das weiss eigentlich der Seitentyp bzw. womöglich der Controller. Ich habe deshalb für eine zukünftige Version von Contao folgendes festgehalten: https://github.com/contao/core-bundle/issues/242 - liesse sich auch problemlos in einer 4.x implementieren, da die alte `Search` Klasse einfach als deprecated markiert werden könnte.

**Comment by aschempp** [comment]
Ich habe ein neues Buch für die Dokumentation von Entwicklerinfos für Contao 4 erstellt:
https://docs.contao.org/
https://docs.contao.org/books/contao4-migration/

Inhalte gerne als PR an https://github.com/contao/docs/tree/master/contao4-migration

Die Navigation (https://github.com/contao/docs/blob/master/contao4-migration/SUMMARY.md) ist ein erster Entwurf, gerne auch PRs für weitere Inhaltsvorschläge.

**Comment by leofeyer** [comment]
+1
